/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Input parameters for the solver, received from Node.js.
 * NAPI-RS + serde handles automatic V8 Object → Rust Struct conversion.
 *
 * Field aliases allow both naming conventions:
 *   - Cloud uses: format, num_players, position
 *   - Edge uses:  game_variant, num_opponents
 */
export interface SolveParams {
  /** 0 = PLO5, 1 = PLO6, 2 = NLH  (alias: game_variant) */
  format: number
  /** 0 = Preflop, 1 = Flop, 2 = Turn, 3 = River */
  street: number
  /** Hero cards as card IDs (0-51) */
  heroCards: Array<number>
  /** Board cards as card IDs (0-51) */
  boardCards: Array<number>
  /** Known dead/folded cards */
  deadCards: Array<number>
  /** Pot size in BB×100 (fixed-point) */
  potBb100: number
  /** Hero stack in BB×100 */
  heroStack: number
  /** Villain stacks in BB×100 */
  villainStacks: Array<number>
  /** Hero position (0=BTN, 1=SB, 2=BB, 3=UTG, 4=MP, 5=CO) */
  position: number
  /** Number of players remaining (alias: num_opponents — adds 1 internally) */
  numPlayers: number
}
/** Output from the solver, sent back to Node.js. */
export interface SolveResult {
  /** Recommended action (0=Fold, 1=Check, 2=Call, 3=Raise, 4=AllIn) */
  action: number
  /** Raise amount in BB×100 */
  raiseAmountBb100: number
  /** Hero equity [0.0, 1.0] */
  equity: number
  /** Expected value in BB×100 */
  evBb100: number
  /** Action frequencies */
  freqFold: number
  freqCheck: number
  freqCall: number
  freqRaise: number
  freqAllin: number
  /** Confidence in the solution [0.0, 1.0] */
  confidence: number
}
/**
 * Initialize the engine. Loads CFR strategy tables into memory.
 * Called once at server startup.
 */
export declare function init(): void
/** Return the engine version string. */
export declare function version(): string
/**
 * Solve a game state. This is the main entry point called per-decision.
 *
 * Flow:
 * 1. Parse cards from IDs
 * 2. Compute equity via Monte Carlo (Omaha-aware)
 * 3. Determine optimal mixed strategy
 * 4. Return action + frequencies
 */
export declare function solve(params: SolveParams): SolveResult
/**
 * Raw 5-card hand evaluation. Returns a rank where lower = better.
 * Royal flush = 1, worst high card = 7462.
 */
export declare function evaluate(cards: Array<number>): number
/**
 * Compute pure equity for a hand against random opponents.
 * Uses Monte Carlo simulation with Omaha rules.
 */
export declare function equity(heroCards: Array<number>, boardCards: Array<number>, sims: number): number
